# Global configuration
global:
    scrape_interval: 15s  # How often to scrape targets (15 seconds)
    evaluation_interval: 15s  # How often to evaluate rules (15 seconds)

# Scrape configuration for your .NET application
scrape_configs:
    - job_name: 'API-GATE-WAY'
      static_configs:
          - targets: ['host.docker.internal:7277']  # Replace with your .NET app's endpoint
